Helioviewer-Project/helios

Configuration.js
UI/source_controls.js

Limit the max number of dates that can be queried at once

---

index.html

Add SDO sources to the dropdown

---

Scene/sun.js
Scene/three/mesh_loader.js
Scene/three/model_builder.js

Set opacity

---

Scene/model.js
Scene/scene.js
Scene/three/model_builder.js
UI/source_controls.js

Add polygon offsets to simulate layering images

---

Scene/model.js
Scene/three/model_builder.js

Move the model update code into model_builder.js and fix error

---

Scene/three/model_builder.js

Update multiplier for polygon offset

---

Scene/scene.js
Scene/three/model_builder.js
UI/source_controls.js
common/resolution_lookup.js
index.html
resources/models/sun_model.gltf

Also fixes animation for a bug introduced when I changed this._models to be a dictionary instead of an array.
Updates the polygon offset to an even larger number

Add resolutions and handle resolution being dependent on image source

---

Configuration.js
UI/source_controls.js
common/observers.js
index.html
resources/css/main.css

Add UI for displaying and removing sources

---

UI/source_controls.js

Update UI time when scene time updates

---

Scene/model.js
Scene/model_factory.js
Scene/scene.js
UI/source_controls.js
index.html
resources/css/source_controls.css

Add functionality to lock the camera to an observer

---

common/resolution_lookup.js

No fake upscaling

---

Configuration.js
Scene/model.js
UI/source_controls.js
resources/css/source_controls.css

Change the color of the model timestamp as it strays from the scene time

---

Configuration.js
UI/animation_controls.js
UI/date_range_picker.js
UI/source_controls.js
index.html

Update UI to request number of frames instead of cadence

---

Configuration.js
README.md
Scene/three/model_builder.js
common/resolution_lookup.js
index.html

Add Stereo

---

Configuration.js
common/resolution_lookup.js
index.html

Add SOHO sources

---

UI/source_controls.js

Update date format in UI to more readable format

---

Scene/scene.js

Add function for getting the scene's time range

---

Configuration.js
UI/date_range_picker.js
index.html
package-lock.json
package.json

This breaks animation, because animation depends on the date range inputs. so #44 needs to be done first before this is merged.

Add flatpickr datetimepicker for date ranges

---

API/helioviewer.js
Configuration.js
Scene/scene.js
Scene/three/model_builder.js
Scene/three/three_scene.js
UI/events.js
index.html

Fixes #72
Also includes some other patches fixes like updating the page title and removing the tween during animation (this was causing it to not animate at all).

Pre launch config

---

Scene/model.js
Scene/scene.js
UI/animation_controls.js
UI/helioviewer_movie.js
index.html

Update animation to rely on FPS exclusively, not duration.

change animation to rely on frame count

---

index.html

Removed dead code of the problem: #79.

Remove dead launcher code

---

Helios.js
Scene/scene.js
UI/source_controls.js
UI/video_manager.js

First step in being able to save/load/share sessions.

Implement a class that is capable of saving and loading scenes

---

.babelrc
package-lock.json
package.json
src/Configuration.js
src/UI/helioviewer_movie.js
src/UI/navigation/control_tabs/components/datasource_picker.js
src/UI/navigation/controls.tsx
src/UI/navigation/navbar.css
src/UI/navigation/navbar.tsx
src/UI/navigation/navbutton.css
src/UI/navigation/navbutton.tsx
src/common/jhelioviewer.ts
src/common/sources.ts
test/animation.test.tsx
test/configuration.test.js
test/datasource_picker.test.tsx
test/helioviewer_movie.test.ts
test/jhelioviewer.test.ts
test/sources.test.ts
tsconfig.json
webpack.config.js

If JHelioviewer is running, then the JHV icon will show up in the sidebar.
Clicking it will send the current viewport to JHelioviewer.

Add Jhv support

---

src/API/helioviewer.js
src/API/preferences.ts
src/Helios.tsx
src/Images/database.js
src/Images/image_finder.js
src/Scene/model_factory.js
src/Scene/scene.js
src/UI/navigation/control_tabs/preference_controls.tsx
test/preferences.test.ts

Allows user to set image format to png, webp, or jpg. Default is 1k jpg, seems to look nice.

Enable image format options
